name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyscaffold

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1.32.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          custom_tag: v0.0.0
          tag_prefix: 'v'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the package
        run: |
          tox
          tox -e docs
          tox -e build


    
  
